# Generated by Django 5.0.1 on 2024-09-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobstable',
            old_name='employement_type',
            new_name='employment_type',
        ),
    ]
